# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20180424_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
